# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: duel_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import duel_enum_pb2 as duel__enum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='duel_data.proto',
  package='YGOpen.Proto.Duel',
  syntax='proto3',
  serialized_options=b'H\003\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x64uel_data.proto\x12\x11YGOpen.Proto.Duel\x1a\x0f\x64uel_enum.proto\"\x89\x01\n\x05\x43hain\x12,\n\ncard_place\x18\x01 \x01(\x0b\x32\x18.YGOpen.Proto.Duel.Place\x12\'\n\x05place\x18\x02 \x01(\x0b\x32\x18.YGOpen.Proto.Duel.Place\x12)\n\x06\x65\x66\x66\x65\x63t\x18\x03 \x01(\x0b\x32\x19.YGOpen.Proto.Duel.Effect\"&\n\x07\x43ounter\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\"%\n\x06\x45\x66\x66\x65\x63t\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\r\"x\n\x05Place\x12*\n\x03\x63on\x18\x01 \x01(\x0e\x32\x1d.YGOpen.Proto.Duel.Controller\x12(\n\x03loc\x18\x02 \x01(\x0e\x32\x1b.YGOpen.Proto.Duel.Location\x12\x0b\n\x03seq\x18\x03 \x01(\r\x12\x0c\n\x04oseq\x18\x04 \x01(\x11\x42\x05H\x03\xf8\x01\x01\x62\x06proto3'
  ,
  dependencies=[duel__enum__pb2.DESCRIPTOR,])




_CHAIN = _descriptor.Descriptor(
  name='Chain',
  full_name='YGOpen.Proto.Duel.Chain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='card_place', full_name='YGOpen.Proto.Duel.Chain.card_place', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='place', full_name='YGOpen.Proto.Duel.Chain.place', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='effect', full_name='YGOpen.Proto.Duel.Chain.effect', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=193,
)


_COUNTER = _descriptor.Descriptor(
  name='Counter',
  full_name='YGOpen.Proto.Duel.Counter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='YGOpen.Proto.Duel.Counter.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='YGOpen.Proto.Duel.Counter.count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=233,
)


_EFFECT = _descriptor.Descriptor(
  name='Effect',
  full_name='YGOpen.Proto.Duel.Effect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='YGOpen.Proto.Duel.Effect.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='YGOpen.Proto.Duel.Effect.index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=272,
)


_PLACE = _descriptor.Descriptor(
  name='Place',
  full_name='YGOpen.Proto.Duel.Place',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='con', full_name='YGOpen.Proto.Duel.Place.con', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loc', full_name='YGOpen.Proto.Duel.Place.loc', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seq', full_name='YGOpen.Proto.Duel.Place.seq', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='oseq', full_name='YGOpen.Proto.Duel.Place.oseq', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=394,
)

_CHAIN.fields_by_name['card_place'].message_type = _PLACE
_CHAIN.fields_by_name['place'].message_type = _PLACE
_CHAIN.fields_by_name['effect'].message_type = _EFFECT
_PLACE.fields_by_name['con'].enum_type = duel__enum__pb2._CONTROLLER
_PLACE.fields_by_name['loc'].enum_type = duel__enum__pb2._LOCATION
DESCRIPTOR.message_types_by_name['Chain'] = _CHAIN
DESCRIPTOR.message_types_by_name['Counter'] = _COUNTER
DESCRIPTOR.message_types_by_name['Effect'] = _EFFECT
DESCRIPTOR.message_types_by_name['Place'] = _PLACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chain = _reflection.GeneratedProtocolMessageType('Chain', (_message.Message,), {
  'DESCRIPTOR' : _CHAIN,
  '__module__' : 'duel_data_pb2'
  # @@protoc_insertion_point(class_scope:YGOpen.Proto.Duel.Chain)
  })
_sym_db.RegisterMessage(Chain)

Counter = _reflection.GeneratedProtocolMessageType('Counter', (_message.Message,), {
  'DESCRIPTOR' : _COUNTER,
  '__module__' : 'duel_data_pb2'
  # @@protoc_insertion_point(class_scope:YGOpen.Proto.Duel.Counter)
  })
_sym_db.RegisterMessage(Counter)

Effect = _reflection.GeneratedProtocolMessageType('Effect', (_message.Message,), {
  'DESCRIPTOR' : _EFFECT,
  '__module__' : 'duel_data_pb2'
  # @@protoc_insertion_point(class_scope:YGOpen.Proto.Duel.Effect)
  })
_sym_db.RegisterMessage(Effect)

Place = _reflection.GeneratedProtocolMessageType('Place', (_message.Message,), {
  'DESCRIPTOR' : _PLACE,
  '__module__' : 'duel_data_pb2'
  # @@protoc_insertion_point(class_scope:YGOpen.Proto.Duel.Place)
  })
_sym_db.RegisterMessage(Place)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
