# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: duel_answer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='duel_answer.proto',
  package='YGOpen.Proto.Duel',
  syntax='proto3',
  serialized_options=b'H\003\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64uel_answer.proto\x12\x11YGOpen.Proto.DuelB\x05H\x03\xf8\x01\x01\x62\x06proto3'
)



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
