# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replay.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import duel_msg_pb2 as duel__msg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='replay.proto',
  package='YGOpen.Proto',
  syntax='proto3',
  serialized_options=b'H\003\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0creplay.proto\x12\x0cYGOpen.Proto\x1a\x0e\x64uel_msg.proto\"\xdd\x03\n\x06Replay\x12-\n\x06stream\x18\x01 \x01(\x0b\x32\x1b.YGOpen.Proto.Replay.StreamH\x00\x12\x42\n\x11\x63ompressed_stream\x18\x02 \x01(\x0b\x32%.YGOpen.Proto.Replay.CompressedStreamH\x00\x1a\x88\x01\n\x06Stream\x12\x31\n\x06\x62locks\x18\x01 \x03(\x0b\x32!.YGOpen.Proto.Replay.Stream.Block\x1aK\n\x05\x42lock\x12\x16\n\x0etime_offset_ms\x18\x01 \x01(\r\x12%\n\x03msg\x18\x02 \x01(\x0b\x32\x16.YGOpen.Proto.Duel.MsgH\x00\x42\x03\n\x01t\x1a\xcf\x01\n\x10\x43ompressedStream\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x12\x19\n\x11uncompressed_size\x18\x02 \x01(\x04\x12\x38\n\x03lz4\x18\x03 \x01(\x0b\x32).YGOpen.Proto.Replay.CompressedStream.LZ4H\x00\x12:\n\x04lzma\x18\x04 \x01(\x0b\x32*.YGOpen.Proto.Replay.CompressedStream.LZMAH\x00\x1a\x05\n\x03LZ4\x1a\x06\n\x04LZMAB\x0b\n\talgorithmB\x03\n\x01tB\x05H\x03\xf8\x01\x01\x62\x06proto3'
  ,
  dependencies=[duel__msg__pb2.DESCRIPTOR,])




_REPLAY_STREAM_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='YGOpen.Proto.Replay.Stream.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_offset_ms', full_name='YGOpen.Proto.Replay.Stream.Block.time_offset_ms', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='YGOpen.Proto.Replay.Stream.Block.msg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='t', full_name='YGOpen.Proto.Replay.Stream.Block.t',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=234,
  serialized_end=309,
)

_REPLAY_STREAM = _descriptor.Descriptor(
  name='Stream',
  full_name='YGOpen.Proto.Replay.Stream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blocks', full_name='YGOpen.Proto.Replay.Stream.blocks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REPLAY_STREAM_BLOCK, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=309,
)

_REPLAY_COMPRESSEDSTREAM_LZ4 = _descriptor.Descriptor(
  name='LZ4',
  full_name='YGOpen.Proto.Replay.CompressedStream.LZ4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=498,
)

_REPLAY_COMPRESSEDSTREAM_LZMA = _descriptor.Descriptor(
  name='LZMA',
  full_name='YGOpen.Proto.Replay.CompressedStream.LZMA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=506,
)

_REPLAY_COMPRESSEDSTREAM = _descriptor.Descriptor(
  name='CompressedStream',
  full_name='YGOpen.Proto.Replay.CompressedStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='YGOpen.Proto.Replay.CompressedStream.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uncompressed_size', full_name='YGOpen.Proto.Replay.CompressedStream.uncompressed_size', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lz4', full_name='YGOpen.Proto.Replay.CompressedStream.lz4', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lzma', full_name='YGOpen.Proto.Replay.CompressedStream.lzma', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REPLAY_COMPRESSEDSTREAM_LZ4, _REPLAY_COMPRESSEDSTREAM_LZMA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='algorithm', full_name='YGOpen.Proto.Replay.CompressedStream.algorithm',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=312,
  serialized_end=519,
)

_REPLAY = _descriptor.Descriptor(
  name='Replay',
  full_name='YGOpen.Proto.Replay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream', full_name='YGOpen.Proto.Replay.stream', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compressed_stream', full_name='YGOpen.Proto.Replay.compressed_stream', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REPLAY_STREAM, _REPLAY_COMPRESSEDSTREAM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='t', full_name='YGOpen.Proto.Replay.t',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=47,
  serialized_end=524,
)

_REPLAY_STREAM_BLOCK.fields_by_name['msg'].message_type = duel__msg__pb2._MSG
_REPLAY_STREAM_BLOCK.containing_type = _REPLAY_STREAM
_REPLAY_STREAM_BLOCK.oneofs_by_name['t'].fields.append(
  _REPLAY_STREAM_BLOCK.fields_by_name['msg'])
_REPLAY_STREAM_BLOCK.fields_by_name['msg'].containing_oneof = _REPLAY_STREAM_BLOCK.oneofs_by_name['t']
_REPLAY_STREAM.fields_by_name['blocks'].message_type = _REPLAY_STREAM_BLOCK
_REPLAY_STREAM.containing_type = _REPLAY
_REPLAY_COMPRESSEDSTREAM_LZ4.containing_type = _REPLAY_COMPRESSEDSTREAM
_REPLAY_COMPRESSEDSTREAM_LZMA.containing_type = _REPLAY_COMPRESSEDSTREAM
_REPLAY_COMPRESSEDSTREAM.fields_by_name['lz4'].message_type = _REPLAY_COMPRESSEDSTREAM_LZ4
_REPLAY_COMPRESSEDSTREAM.fields_by_name['lzma'].message_type = _REPLAY_COMPRESSEDSTREAM_LZMA
_REPLAY_COMPRESSEDSTREAM.containing_type = _REPLAY
_REPLAY_COMPRESSEDSTREAM.oneofs_by_name['algorithm'].fields.append(
  _REPLAY_COMPRESSEDSTREAM.fields_by_name['lz4'])
_REPLAY_COMPRESSEDSTREAM.fields_by_name['lz4'].containing_oneof = _REPLAY_COMPRESSEDSTREAM.oneofs_by_name['algorithm']
_REPLAY_COMPRESSEDSTREAM.oneofs_by_name['algorithm'].fields.append(
  _REPLAY_COMPRESSEDSTREAM.fields_by_name['lzma'])
_REPLAY_COMPRESSEDSTREAM.fields_by_name['lzma'].containing_oneof = _REPLAY_COMPRESSEDSTREAM.oneofs_by_name['algorithm']
_REPLAY.fields_by_name['stream'].message_type = _REPLAY_STREAM
_REPLAY.fields_by_name['compressed_stream'].message_type = _REPLAY_COMPRESSEDSTREAM
_REPLAY.oneofs_by_name['t'].fields.append(
  _REPLAY.fields_by_name['stream'])
_REPLAY.fields_by_name['stream'].containing_oneof = _REPLAY.oneofs_by_name['t']
_REPLAY.oneofs_by_name['t'].fields.append(
  _REPLAY.fields_by_name['compressed_stream'])
_REPLAY.fields_by_name['compressed_stream'].containing_oneof = _REPLAY.oneofs_by_name['t']
DESCRIPTOR.message_types_by_name['Replay'] = _REPLAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Replay = _reflection.GeneratedProtocolMessageType('Replay', (_message.Message,), {

  'Stream' : _reflection.GeneratedProtocolMessageType('Stream', (_message.Message,), {

    'Block' : _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
      'DESCRIPTOR' : _REPLAY_STREAM_BLOCK,
      '__module__' : 'replay_pb2'
      # @@protoc_insertion_point(class_scope:YGOpen.Proto.Replay.Stream.Block)
      })
    ,
    'DESCRIPTOR' : _REPLAY_STREAM,
    '__module__' : 'replay_pb2'
    # @@protoc_insertion_point(class_scope:YGOpen.Proto.Replay.Stream)
    })
  ,

  'CompressedStream' : _reflection.GeneratedProtocolMessageType('CompressedStream', (_message.Message,), {

    'LZ4' : _reflection.GeneratedProtocolMessageType('LZ4', (_message.Message,), {
      'DESCRIPTOR' : _REPLAY_COMPRESSEDSTREAM_LZ4,
      '__module__' : 'replay_pb2'
      # @@protoc_insertion_point(class_scope:YGOpen.Proto.Replay.CompressedStream.LZ4)
      })
    ,

    'LZMA' : _reflection.GeneratedProtocolMessageType('LZMA', (_message.Message,), {
      'DESCRIPTOR' : _REPLAY_COMPRESSEDSTREAM_LZMA,
      '__module__' : 'replay_pb2'
      # @@protoc_insertion_point(class_scope:YGOpen.Proto.Replay.CompressedStream.LZMA)
      })
    ,
    'DESCRIPTOR' : _REPLAY_COMPRESSEDSTREAM,
    '__module__' : 'replay_pb2'
    # @@protoc_insertion_point(class_scope:YGOpen.Proto.Replay.CompressedStream)
    })
  ,
  'DESCRIPTOR' : _REPLAY,
  '__module__' : 'replay_pb2'
  # @@protoc_insertion_point(class_scope:YGOpen.Proto.Replay)
  })
_sym_db.RegisterMessage(Replay)
_sym_db.RegisterMessage(Replay.Stream)
_sym_db.RegisterMessage(Replay.Stream.Block)
_sym_db.RegisterMessage(Replay.CompressedStream)
_sym_db.RegisterMessage(Replay.CompressedStream.LZ4)
_sym_db.RegisterMessage(Replay.CompressedStream.LZMA)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
